<template>
  <v-footer
    dark
    height="auto"
  >
    <v-layout
      justify-center
      row
      wrap
    >
      <v-flex
        py-3
        text-xs-center
        white--text
        xs12
      >
        &copy;2019 — <strong>Edward Vuetify</strong>
      </v-flex>
    </v-layout>
  </v-footer>
</template>